name: Build

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    uses: HeavenCube/HCPlugins-actions/.github/workflows/build.yml@main
    with:
      project-name: HCAdvancementsRedirect
      artifact-path: build/libs/HCAdvancementsRedirect-*.jar
      core-source: true
    secrets: inherit
